// GEGENEREERD door iconen-voorstel/_bron/maak-app-iconen.mjs uit iconen.json. Niet met de hand wijzigen.
import type { LucideIcon } from 'lucide-react';
import {
  Archive,
  ArrowLeft,
  BadgeCheck,
  Ban,
  Building2,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarSync,
  Camera,
  Check,
  ChevronDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CircleQuestionMark,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Clock,
  CloudUpload,
  Columns3,
  Copy,
  Download,
  Euro,
  ExternalLink,
  FileClock,
  FileDown,
  FileText,
  Files,
  FolderCheck,
  Funnel,
  Gauge,
  Globe,
  Handshake,
  Hash,
  House,
  ImageMinus,
  ImagePlus,
  Inbox,
  Info,
  ListChecks,
  ListX,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageSquareText,
  OctagonAlert,
  Pencil,
  Phone,
  Plus,
  Printer,
  Repeat,
  RotateCcw,
  Route,
  Search,
  Settings,
  Sigma,
  Signature,
  Star,
  Tag,
  Target,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  WifiOff,
  Wind,
  X,
} from 'lucide-react';
import {
  OilSample,
  OilSampleLabel,
  Resample,
  SamplePoint,
  OilType,
  CopyYear,
  HydraulicCylinder,
  Pump,
  Valve,
  ShipLock,
  Weir,
  Structure,
  StatusPlanned,
  ModuleRounds,
  GpsLive,
  Admin,
  InstallApp,
} from './eigen';

/** Alle iconen die in de portal gebruikt worden. Naam = wat het icoon is (zie STIJL.md, Iconen). */
export const ICONEN = {
  'home': House,
  'arrow-left': ArrowLeft,
  'chevron-down': ChevronDown,
  'menu': Menu,
  'close': X,
  'plus': Plus,
  'pencil': Pencil,
  'trash': Trash2,
  'search': Search,
  'filter': Funnel,
  'download': Download,
  'check': Check,
  'copy': Copy,
  'reset': RotateCcw,
  'select-all': ListChecks,
  'clear-selection': ListX,
  'printer': Printer,
  'columns': Columns3,
  'camera': Camera,
  'image-upload': ImagePlus,
  'image-remove': ImageMinus,
  'file-pdf': FileDown,
  'oil-sample': OilSample,
  'oil-sample-label': OilSampleLabel,
  'resample': Resample,
  'sample-point': SamplePoint,
  'oil-type': OilType,
  'tag': Tag,
  'calendar': Calendar,
  'comment': MessageSquareText,
  'map-pin': MapPin,
  'total': Sigma,
  'copy-year': CopyYear,
  'hydraulic-cylinder': HydraulicCylinder,
  'pump': Pump,
  'valve': Valve,
  'ship-lock': ShipLock,
  'weir': Weir,
  'structure': Structure,
  'status-taken': CircleCheck,
  'status-not-taken': CircleAlert,
  'status-planned': StatusPlanned,
  'status-cancelled': Ban,
  'status-round-open': Circle,
  'status-round-busy': CirclePlay,
  'status-round-done': CircleCheck,
  'module-rounds': ModuleRounds,
  'route': Route,
  'gps-live': GpsLive,
  'module-ultimo': ClipboardList,
  'job': Hash,
  'module-print-calc': Calculator,
  'module-email': Mail,
  'module-acquisitie': Target,
  'company': Building2,
  'website': Globe,
  'external-link': ExternalLink,
  'phone': Phone,
  'mail': Mail,
  'upload': Upload,
  'euro': Euro,
  'star': Star,
  'archive': Archive,
  'clock': Clock,
  'handshake': Handshake,
  'admin': Admin,
  'settings': Settings,
  'audit-log': FileClock,
  'help': CircleQuestionMark,
  'user': User,
  'user-plus': UserPlus,
  'logout': LogOut,
  'install-app': InstallApp,
  'alert-success': BadgeCheck,
  'alert-info': Info,
  'alert-warning': TriangleAlert,
  'alert-danger': OctagonAlert,
  'empty': Inbox,
  'module-inspecties': ClipboardCheck,
  'module-eigen-dossier': FolderCheck,
  'air-leak': Wind,
  'gauge': Gauge,
  'document': FileText,
  'file-bundle': Files,
  'module-contracten': CalendarClock,
  'module-dagrapport': ClipboardPen,
  'signature': Signature,
  'agenda-feed': CalendarSync,
  'offline': WifiOff,
  'verzenden': CloudUpload,
  'interval': Repeat,
} satisfies Record<string, LucideIcon>;

export type IconNaam = keyof typeof ICONEN;
